### ISSUE TITLE
Add "lit mode" easter egg

### ISSUE THREAD

**Issue by jerrypopsoff** [jerrypopsoff/jerrypop#438]
```css
:root {
  --image-filter: invert(1) hue-rotate(180deg) brightness(1.2);
}
```
